### ISSUE TITLE
add Bing as a reverse image search provider

### ISSUE THREAD

**Issue by heptal** [rohitbatra1/Safari-Reverse-Image-Search#1]
Bing's consumer-facing reverse image search is comparable to Yandex's (it's very good)

```js
let queryUrl = `https://www.bing.com/images/search?view=detailv2&iss=sbi&sim=1&q=imgurl:${imageUrl}`
```

**Comment by rohitbatra1** [comment]
I'd like to first implement a menu in the app which allows users to select which search engines they would like to have on so the extension doesn't fill up the context menu with unused options.

I haven't gotten around to doing this yet, but once I do, hopefully soon, i'll be sure to add Bing.

**Comment by rohitbatra1** [comment]
I've added Bing as a search engine in the latest release: [ImageFinder for Safari.app.zip](https://github.com/rohitbatra1/Safari-Reverse-Image-Search/releases/download/v1.1/ImageFinder.for.Safari.app.zip). 

I haven't yet implemented the menu, so this release will not be published on the app store.
